import { h, defineTool, input, btn, card, copy, subtabs, tbl, debounce } from "../core.js";

const SHEETS = {
  git: [["git init", "new repo"], ["git clone <url>", "copy a repo"], ["git status", "what changed"], ["git add -A", "stage everything"], ["git add -p", "stage hunks interactively"], ["git commit -m 'msg'", "commit staged"], ["git commit --amend --no-edit", "add to last commit"], ["git log --oneline --graph --all", "pretty history"], ["git diff / git diff --staged", "unstaged / staged changes"], ["git switch -c <branch>", "create + switch branch"], ["git switch -", "back to previous branch"], ["git merge <branch>", "merge into current"], ["git rebase -i HEAD~3", "squash / reorder last 3"], ["git rebase --continue / --abort", "resolve or bail"], ["git stash / git stash pop", "shelve / restore work"], ["git stash list", "see stashes"], ["git restore <file>", "discard working changes"], ["git restore --staged <file>", "unstage"], ["git reset --soft HEAD~1", "undo commit, keep changes staged"], ["git reset --hard origin/main", "match remote exactly (destructive)"], ["git revert <sha>", "undo a commit safely"], ["git cherry-pick <sha>", "copy one commit"], ["git fetch --prune", "update remote refs, drop deleted"], ["git pull --rebase", "pull without merge commits"], ["git push -u origin <branch>", "push + set upstream"], ["git push --force-with-lease", "safer force push"], ["git tag -a v1.0 -m 'v1'", "annotated tag"], ["git blame -L 10,20 file", "who changed lines"], ["git bisect start/good/bad", "binary-search a bug"], ["git reflog", "find lost commits"], ["git worktree add ../dir branch", "second working copy"], ["git config --global alias.co checkout", "alias"], ["git rm --cached <file>", "untrack but keep file"], ["git clean -fdn", "preview deleting untracked (drop -n to do it)"]],
  bash: [["ls -lah", "list with sizes, hidden"], ["cd -", "previous directory"], ["pwd", "where am I"], ["mkdir -p a/b/c", "nested dirs"], ["cp -r src dst", "copy recursively"], ["mv a b", "move / rename"], ["rm -rf dir", "delete recursively (careful)"], ["find . -name '*.log' -mtime +7", "files older than 7 days"], ["find . -type f -size +100M", "big files"], ["grep -rn 'text' .", "search recursively with line numbers"], ["grep -ril 'text' .", "just filenames, case-insensitive"], ["rg 'pattern' -t js", "ripgrep by type"], ["cat f | head -n 20 / tail -f", "first lines / follow"], ["less +F file", "pager that follows"], ["wc -l file", "count lines"], ["sort | uniq -c | sort -rn", "frequency count"], ["cut -d, -f2 file.csv", "column 2 of csv"], ["awk '{print $1}'", "first field"], ["sed -i '' 's/a/b/g' file", "replace in place (macOS)"], ["xargs -I{} cmd {}", "run cmd per input line"], ["cmd1 | tee out.txt", "print and save"], ["cmd > out 2>&1", "redirect stdout+stderr"], ["cmd &; jobs; fg", "background / list / foreground"], ["nohup cmd &", "survive logout"], ["ctrl-r", "search history"], ["!!", "repeat last command"], ["$(cmd) / `cmd`", "command substitution"], ["${VAR:-default}", "default value"], ["for f in *.txt; do …; done", "loop files"], ["if [ -f f ]; then …; fi", "test file exists"], ["chmod +x script.sh", "make executable"], ["chown user:group file", "change owner"], ["du -sh * | sort -h", "folder sizes"], ["df -h", "disk free"], ["ps aux | grep name", "find process"], ["kill -9 <pid>", "force kill"], ["lsof -i :3000", "who's on port 3000"], ["curl -sS -o /dev/null -w '%{http_code}' url", "just the status"], ["ssh -i key user@host", "ssh with key"], ["scp file user@host:/path", "copy over ssh"], ["rsync -avz src/ host:dst/", "sync dirs"], ["tar -czf a.tgz dir / tar -xzf a.tgz", "compress / extract"], ["alias ll='ls -la'", "shortcut"], ["export PATH=\"$HOME/bin:$PATH\"", "add to PATH"]],
  vim: [["i / a / o", "insert before / after / new line"], ["Esc", "back to normal mode"], [":w / :q / :wq / :q!", "save / quit / both / discard"], ["h j k l", "left down up right"], ["w / b / e", "word forward / back / end"], ["0 / ^ / $", "line start / first char / end"], ["gg / G", "top / bottom"], ["{ / }", "paragraph up / down"], ["ctrl-d / ctrl-u", "half page down / up"], [":42", "go to line 42"], ["x / dd / dw", "delete char / line / word"], ["yy / yw / p / P", "yank line / word, paste after / before"], ["u / ctrl-r", "undo / redo"], [".", "repeat last change"], ["cw / ciw / ci\"", "change word / inner word / inside quotes"], ["dt) / df)", "delete till / through )"], ["v / V / ctrl-v", "visual char / line / block"], ["> / <", "indent / dedent (visual)"], ["/pattern  n  N", "search, next, previous"], [":%s/a/b/g", "replace all"], [":%s/a/b/gc", "replace with confirm"], ["*", "search word under cursor"], ["%", "jump to matching bracket"], ["ma / 'a", "set mark a / jump to it"], ["qa … q / @a", "record macro a / play it"], [":e file", "open file"], [":sp / :vsp", "split horizontal / vertical"], ["ctrl-w h/j/k/l", "move between splits"], [":set nu / :set nonu", "line numbers"], [":noh", "clear search highlight"], ["zz / zt / zb", "center / top / bottom cursor line"], ["~", "toggle case"], ["J", "join lines"], [":r !cmd", "insert command output"], ["ctrl-o / ctrl-i", "jump back / forward"]],
  docker: [["docker ps -a", "all containers"], ["docker images", "local images"], ["docker run -it --rm image sh", "throwaway shell"], ["docker run -d -p 8080:80 --name web nginx", "detached with port map"], ["docker run -v $(pwd):/app image", "mount current dir"], ["docker exec -it name sh", "shell into running container"], ["docker logs -f name", "follow logs"], ["docker stop / start / restart name", "lifecycle"], ["docker rm -f name", "remove container"], ["docker rmi image", "remove image"], ["docker build -t name:tag .", "build from Dockerfile"], ["docker build --no-cache", "rebuild fully"], ["docker pull / push image", "registry"], ["docker tag a b", "retag"], ["docker inspect name", "everything about it"], ["docker stats", "live resource use"], ["docker system prune -a", "delete unused everything"], ["docker volume ls / prune", "volumes"], ["docker network ls", "networks"], ["docker compose up -d", "start stack detached"], ["docker compose down -v", "stop and drop volumes"], ["docker compose logs -f svc", "follow one service"], ["docker compose exec svc sh", "shell into service"], ["docker compose ps", "stack status"], ["docker compose build --no-cache", "rebuild images"], ["docker cp name:/path ./local", "copy out of container"], ["docker save img | gzip > img.tgz", "export image"], ["docker load < img.tgz", "import image"]],
  "npm / pnpm": [["npm init -y", "new package.json"], ["npm i pkg / npm i -D pkg", "add dep / dev dep"], ["npm i pkg@1.2.3", "pinned version"], ["npm un pkg", "remove"], ["npm ls --depth=0", "top-level deps"], ["npm outdated / npm update", "check / update"], ["npm run script", "run package script"], ["npm run script -- --flag", "pass args"], ["npx pkg", "run without installing"], ["npm ci", "clean install from lockfile"], ["npm cache clean --force", "nuke cache"], ["npm audit / npm audit fix", "vulnerabilities"], ["npm version patch|minor|major", "bump + tag"], ["npm publish --access public", "publish"], ["npm link / npm link pkg", "local package dev"], ["npm view pkg versions", "available versions"], ["pnpm i / pnpm add pkg", "pnpm equivalents"], ["pnpm dlx pkg", "pnpm's npx"], ["pnpm -r run build", "recursive in workspace"], ["yarn / yarn add pkg", "yarn equivalents"], ["node -e \"code\"", "one-liner"], ["node --watch app.js", "restart on change"], ["node --inspect app.js", "debugger"], ["nvm use 22 / nvm install --lts", "node versions"], ["npm config set registry <url>", "custom registry"]],
  markdown: [["# H1  ## H2  ### H3", "headings"], ["**bold**  *italic*  ~~strike~~", "emphasis"], ["`code`", "inline code"], ["```js … ```", "code block with language"], ["- item / 1. item", "lists"], ["- [ ] todo / - [x] done", "task list"], ["> quote", "blockquote"], ["[text](url \"title\")", "link"], ["![alt](src)", "image"], ["<https://auto.link>", "autolink"], ["| a | b |\\n|---|---|", "table"], ["|:---|---:|", "align left / right"], ["---", "horizontal rule"], ["line  ␣␣", "two trailing spaces = line break"], ["\\*", "escape a character"], ["[^1] … [^1]: note", "footnote (GFM)"], ["<details><summary>…</summary>", "collapsible (HTML)"], ["Term\\n: definition", "definition list (some flavours)"], ["$x^2$", "math (some flavours)"], ["<!-- comment -->", "hidden comment"]],
  "python": [["python3 -m venv .venv && source .venv/bin/activate", "virtual env"], ["pip install -r requirements.txt", "install deps"], ["pip freeze > requirements.txt", "pin deps"], ["python -m http.server 8000", "static server"], ["python -m json.tool file.json", "pretty json"], ["python -c \"import this\"", "one-liner"], ["[x*2 for x in xs if x]", "list comprehension"], ["{k: v for k, v in pairs}", "dict comprehension"], ["f\"{value:.2f} {name!r}\"", "f-string format / repr"], ["a, *rest = xs", "unpacking"], ["with open(p) as f: data = f.read()", "file read"], ["for i, x in enumerate(xs, 1)", "index + value"], ["for a, b in zip(xs, ys)", "parallel iterate"], ["sorted(xs, key=lambda x: x.age, reverse=True)", "sort by key"], ["from collections import Counter, defaultdict", "handy containers"], ["from pathlib import Path; Path('a').glob('*.py')", "paths"], ["import json; json.dumps(obj, indent=2)", "json out"], ["try: … except ValueError as e: … finally:", "exceptions"], ["def f(*args, **kwargs):", "varargs"], ["@dataclass class P: x: int = 0", "dataclass"], ["if __name__ == '__main__':", "script entry"], ["breakpoint()", "debugger"], ["python -m pytest -x -q", "run tests, stop on first fail"], ["python -m timeit 'code'", "benchmark"]],
  "js arrays": [["arr.map(fn)", "transform"], ["arr.filter(fn)", "keep matching"], ["arr.reduce((acc, x) => acc + x, 0)", "fold"], ["arr.find(fn) / findIndex / findLast", "first match"], ["arr.some(fn) / every(fn)", "any / all"], ["arr.includes(x)", "contains"], ["arr.flat(depth) / flatMap(fn)", "flatten"], ["arr.at(-1)", "last element"], ["[...new Set(arr)]", "dedupe"], ["arr.toSorted((a,b) => a-b)", "sorted copy (non-mutating)"], ["arr.toReversed() / toSpliced()", "non-mutating variants"], ["arr.sort((a, b) => a.localeCompare(b))", "string sort"], ["Object.groupBy(arr, x => x.type)", "group into object"], ["arr.slice(1, 3) / splice(i, 1)", "copy range / remove in place"], ["Array.from({length: n}, (_, i) => i)", "range"], ["arr.join(', ')", "to string"], ["structuredClone(obj)", "deep copy"], ["Object.entries(o) / fromEntries", "object ⇄ pairs"], ["arr.forEach(fn)", "loop (no return)"], ["for (const [i, x] of arr.entries())", "index loop"], ["Promise.all(arr.map(async…))", "parallel async"], ["await Promise.allSettled(ps)", "never throws"], ["arr.length = 0", "clear in place"], ["Math.max(...arr)", "max"]],
  http: [["GET", "read — safe, cacheable"], ["POST", "create / action — not idempotent"], ["PUT", "replace whole resource — idempotent"], ["PATCH", "partial update"], ["DELETE", "remove — idempotent"], ["HEAD", "GET without body"], ["OPTIONS", "CORS preflight / capabilities"], ["200 / 201 / 204", "ok / created / no content"], ["301 / 302 / 304", "moved permanently / found / not modified"], ["400 / 401 / 403 / 404", "bad request / unauthenticated / forbidden / not found"], ["409 / 422 / 429", "conflict / unprocessable / rate limited"], ["500 / 502 / 503 / 504", "server error / bad gateway / unavailable / timeout"], ["Content-Type: application/json", "body format"], ["Authorization: Bearer <token>", "auth header"], ["Cache-Control: no-store / max-age=3600", "caching"], ["ETag / If-None-Match", "conditional GET"], ["Access-Control-Allow-Origin: *", "CORS allow"], ["Set-Cookie: k=v; HttpOnly; Secure; SameSite=Lax", "cookie flags"], ["Content-Security-Policy", "script/resource allowlist"], ["Strict-Transport-Security", "force HTTPS"], ["X-Forwarded-For", "client IP behind proxy"], ["Accept-Encoding: gzip, br", "compression"], ["Range: bytes=0-1023", "partial content (206)"], ["Retry-After", "when to retry 429/503"]],
  "mac keys": [["⌘ Space", "Spotlight"], ["⌘ Tab", "switch apps"], ["⌘ `", "switch windows of app"], ["⌘ ⇧ 4", "screenshot area (⌃ to clipboard)"], ["⌘ ⇧ 5", "screenshot / record menu"], ["⌘ ⇧ .", "show hidden files (Finder)"], ["⌘ ⌥ Esc", "force quit"], ["⌃ ⌘ Q", "lock screen"], ["⌘ ⌥ D", "toggle Dock"], ["⌘ ,", "preferences"], ["⌘ W / ⌘ Q", "close window / quit app"], ["⌘ H / ⌘ M", "hide / minimise"], ["⌘ ⇧ T", "reopen closed tab"], ["⌘ L", "focus address bar"], ["⌘ ⌥ I", "dev tools"], ["⌃ ← / →", "switch desktops"], ["⌃ ↑", "Mission Control"], ["fn fn", "dictation"], ["⌃ ⌘ Space", "emoji picker"], ["⌥ ⌘ V", "move (cut+paste) in Finder"], ["⌘ ⌫", "move to trash"], ["⇧ ⌘ ⌫", "empty trash"], ["⌥ click volume", "audio device menu"]],
  "windows keys": [["Win", "start menu"], ["Win + V", "clipboard history"], ["Win + Shift + S", "snip screenshot"], ["Win + .", "emoji picker"], ["Win + E", "explorer"], ["Win + D", "show desktop"], ["Win + L", "lock"], ["Win + Tab", "task view"], ["Win + ← / →", "snap windows"], ["Win + number", "taskbar app N"], ["Win + X", "power menu"], ["Win + I", "settings"], ["Win + R", "run"], ["Alt + Tab", "switch windows"], ["Alt + F4", "close"], ["Ctrl + Shift + Esc", "task manager"], ["Ctrl + Shift + T", "reopen tab"], ["F2", "rename"], ["Shift + Delete", "delete permanently"], ["Ctrl + Win + ← / →", "switch virtual desktops"], ["Win + Ctrl + D", "new virtual desktop"], ["PrtScn", "screenshot to clipboard"]],
};

defineTool({
  id: "cheats", name: "Cheat Sheets", icon: "☰", cat: "workspace",
  desc: "Searchable quick references: git, bash, vim, docker, npm, markdown, python, JS arrays, HTTP, OS shortcuts.",
  tags: ["cheat sheet", "reference", "git", "bash", "shell", "vim", "docker", "npm", "markdown", "python", "javascript", "http", "shortcuts", "commands"],
  mount(root) {
    const q = input({ type: "search", placeholder: "search every sheet… (rebase, port, screenshot)" });
    const results = h("div");
    const search = () => { const s = q.value.trim().toLowerCase(); if (!s) return results.replaceChildren(); const hits = []; for (const [sheet, rows] of Object.entries(SHEETS)) for (const [c, d] of rows) if ((c + " " + d).toLowerCase().includes(s)) hits.push([sheet, c, d]); results.replaceChildren(hits.length ? tbl(["sheet", "command", "what"], hits.slice(0, 80).map(([s2, c, d]) => [s2, h("span.copyable.mono", { text: c, onclick: () => copy(c) }), d])) : h("p.hint", { text: "no matches" })); };
    q.addEventListener("input", debounce(search, 80));
    const sheetTab = (name) => () => tbl(["command", "what it does"], SHEETS[name].map(([c, d]) => [h("span.copyable.mono", { text: c, title: "click to copy", onclick: () => copy(c) }), d]));
    root.append(h("div.col", q, results, subtabs(Object.keys(SHEETS).map((k) => ({ id: k.replace(/\W+/g, "-"), label: k, render: sheetTab(k) })), { remember: "cheats.tab" }), h("p.hint", { text: "click any command to copy it" })));
  },
});
